In [6]:
# 1

import pandas as pd
from sqlalchemy import create_engine, text


password = "IronHack2025!"
db_name = "sakila"


connection_string = f'mysql+pymysql://root:{password}@localhost:3306/{db_name}'


engine = create_engine(connection_string)

In [7]:
#2

def rentals_month(engine, month, year):

    query = text(f"SELECT * FROM  rental WHERE MONTH(rental_date) = {month} AND YEAR(rental_date) = {year}")

    with engine.connect() as connection:
        result = connection.execute(query) 
        df = pd.DataFrame(result.all())
    return df

In [17]:

df_result = rentals_month(engine, 5, 2005)


print(df_result.shape)

df_result.head()

(1156, 7)

,rental_id,rental_date,inventory_id,customer_id,return_date,staff_id,last_update
0,1,2005-05-24 22:53:30,367,130,2005-05-26 22:04:30,1,2006-02-15 21:30:53
1,2,2005-05-24 22:54:33,1525,459,2005-05-28 19:40:33,1,2006-02-15 21:30:53
2,3,2005-05-24 23:03:39,1711,408,2005-06-01 22:12:39,1,2006-02-15 21:30:53
3,4,2005-05-24 23:04:41,2452,333,2005-06-03 01:43:41,2,2006-02-15 21:30:53
4,5,2005-05-24 23:05:21,2079,222,2005-06-02 04:33:21,1,2006-02-15 21:30:53

In [27]:
def rental_count_month (df, month,year):
    rental_count = df.groupby('customer_id')[['rental_id']].count()

    column_name = f'rentals_{month}_{year}'
    rental_count = rental_count.rename(columns={'rental_id':column_name})

    return rental_count

In [28]:
df_result1 = rental_count_month(df_result, 5, 2005)
df_result1.head()

             rentals_5_2005
customer_id
1                         2
2                         1
3                         2
5                         3
6                         3

In [33]:
# 3
def compare_rentals(df1, df2):
    
    df_merge = df1.merge(df2,left_index=True, right_index=True, how='inner')

    df_merge['difenece'] = df_merge.iloc[:,1]- df_merge.iloc[:,0]
    
    return df_merge

In [35]:

df_jun = rentals_month(engine, 6, 2005)

# 2. Procesamos Junio (contamos y renombramos)
df_count_jun= rental_count_month(df_jun, 6, 2005)

# 3. ¡Comparamos Mayo vs Junio!
# Usamos tu df_result1 (que es Mayo procesado) y el de Junio
df_comparasion = compare_rentals(df_result1, df_count_jun)

# 4. Vemos el resultado final
df_comparasion.head()

             rentals_5_2005  rentals_6_2005  difenece
customer_id
1                         2               7         5
2                         1               1         0
3                         2               4         2
5                         3               5         2
6                         3               4         1